name:                using-quickcheck
version:             0.1.0.0
synopsis:            Test some basic properties using QuickCheck.

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing

tests:
  test-using-quickcheck:
    main:                UsingQuickCheckTest.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is UsingQuickCheckTest
    dependencies:
      - base ^>= 4.15.1
      - hspec ^>= 2.8.5
      - QuickCheck ^>= 2.14.2
