name:                hangman-testing
version:             0.1.0.0
description:         Test the hangman project
verbatim:
  cabal-version: 3.0

dependencies:
  - base ^>= 4.15.1

extra-source-files:
  - data/dict.txt

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing

library:
  source-dirs: src
  exposed-modules:
    - Hangman
  dependencies:
    - random ^>= 1.2.1
    - split ^>= 0.2.3

executables:
  hangman-testing-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - hangman-testing
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  test-hangman-testing:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
      - hangman-testing
      - hspec ^>= 2.8.5
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is Spec
