name:                make-a-gen-random-generator
version:             0.1.0.0
synopsis:            Make a Gen random generator for the datatype

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing

tests:
  test-make-a-gen-random-generator:
    main:                RandomGenTest.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is RandomGenTest
    dependencies:
      - base ^>= 4.15.1
      - hspec ^>= 2.8.5
      - QuickCheck ^>= 2.14.2
