name:                validating-numbers-into-words
version:             0.1.0.0
synopsis:            Test 'numbers into words' routines
verbatim:
  cabal-version: 3.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing

library:
  source-dirs: src
  dependencies:
    - base ^>= 4.15.1

tests:
  test-validating-numbers-into-words:
    main:                WordNumberTest.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is WordNumberTest
    dependencies:
      - base ^>= 4.15.1
      - hspec ^>= 2.8.5
      - validating-numbers-into-words
