name:                idempotence
version:             0.1.0.0
synopsis:            Use QuickCheck to demonstrate idempotence
verbatim:
  cabal-version: 3.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing

tests:
  test-idempotence:
    main:                IdempotenceTest.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is IdempotenceTest
    dependencies:
      - base ^>= 4.15.1
      - hspec ^>= 2.8.5
      - QuickCheck ^>= 2.14.2
